# Generated by Django 5.0 on 2024-01-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('BRASIL', 'BRA'), ('ESTADOS-UNIDOS', 'USA'), ('ARGENTINA', 'ARG')], max_length=70, null=True)),
            ],
        ),
    ]
